# Generated by Django 3.1.4 on 2020-12-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veb', '0002_auto_20201225_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coors',
            name='price',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
