# Generated by Django 3.1.4 on 2021-01-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veb', '0003_auto_20201225_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coors',
            name='available',
        ),
        migrations.RemoveField(
            model_name='coors',
            name='created',
        ),
        migrations.RemoveField(
            model_name='coors',
            name='updated',
        ),
        migrations.AddField(
            model_name='coors',
            name='href',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coors',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
